# SPDX-FileCopyrightText: 2025 Deutsche Telekom AG and others
# 
# SPDX-License-Identifier: Apache-2.0

version = 1
SPDX-PackageName = "arc-view"
SPDX-PackageSupplier = "Deutsche Telekom AG <opensource@telekom.de>"
SPDX-PackageDownloadLocation = "https://github.com/eclipse-lmos/arc-view"

[[annotations]]
path = ["**/.gitignore", ".editorconfig", "pubspec.lock", "README.md", "analysis_options.yaml", "ios/Runner/Assets.xcassets/LaunchImage.imageset/README.md"]
precedence = "aggregate"
SPDX-FileCopyrightText = "none"
SPDX-License-Identifier = "CC0-1.0"

[[annotations]]
path = ["fonts/**", "windows/runner/resources/app_icon.ico"]
precedence = "override"
SPDX-FileCopyrightText = "The original author or authors."
SPDX-License-Identifier = "Apache-2.0"


[[annotations]]
path = [
    "**/*.plist", "**/*.xc*",
    "screenshot.png",
    "**/Podfile*", "**/*.storyboard",
    "**/*.pbxproj", "**/*.xib",
    "**/*.entitlements", "web/manifest.json",
    "**/Runner/Assets.xcassets/**/Contents.json",
    "**/Runner/Assets.xcassets/**/*icon*.png",
    "ios/Runner/Assets.xcassets/**/LaunchImage*.png",
    ".devcontainer/**",
    ".github/**",
    "**/*Icon-*.png", "web/favicon.png",
    "**/*launcher.png"]
precedence = "override"
SPDX-FileCopyrightText = "2025 Deutsche Telekom AG and others"
SPDX-License-Identifier = "Apache-2.0"
[[annotations]]
path = ["**/*.g.dart", "**/*.freezed.dart", "**/*generated_*", "**/*Generated*", "**/windows/runner/Runner.rc"]
precedence = "override"
SPDX-FileCopyrightText = "2025 Deutsche Telekom AG and others Generated Code"
SPDX-License-Identifier = "Apache-2.0"
